# Game config
discrete: False
height: 96  # Original height of the image
lookback_frames: 6

# Training Hyperparameters
training_config:
  # Training
  batch_size: 64  # Number of samples used for each training iteration
  n_epochs: 3  # Number of epochs to train on each batch of data
  n_steps: 1000000  # Total number of game steps to run during training

  # LR
  max_norm: 1.5
  alpha: 5.0e-5
  lr_decay: 0.98
  lr_decay_step_size: 10 

  # Saving
  save_interval: 25  # Learn iters to save at
  save_video_interval: 50  # Save video interval


# Model config
model_config:
  # Architecture
  d_model: 256  # Dimension of attention head
  num_layers: 4  # Layers of self attention blocks
  d_ff: 1024  # Dimension of feed forward network
  dropout: 0.1  # Dropout in the mid layer

  # PPO
  gae_lambda: 0.95  # Generalized Advantage Estimation lambda parameter
  policy_clip: 0.2
  value_clip_range: 0.1
  gamma: 0.99  # Discount factor for future rewards
  N: 4096  # Number of steps between learning iterations
  log_clamp_lower: -2.0
  log_clamp_upper: 0.5
  
  # Entropy
  entropy_coef: 0.001