/**:
  ros__parameters:
    leader_topic: "/leader/joint_states"
    fwd_topic: "/follower/forward_controller/commands"

    # Timing
    publish_rate_hz: 50.0
    stale_timeout_s: 0.25 # Stop if no leader data for this long

    # Joint Names
    arm_joints:
      - "shoulder_pan"
      - "shoulder_lift"
      - "elbow_flex"
      - "wrist_flex"
      - "wrist_roll"
      - "gripper"
